### ISSUE TITLE
 android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder

### ISSUE THREAD

**Issue by Liberations** [Rairmmd/AndMqtt#4]
`java.lang.ClassCastException: android.os.BinderProxy cannot be cast to org.eclipse.paho.android.service.MqttServiceBinder
        at org.eclipse.paho.android.service.MqttAndroidClient$MyServiceConnection.onServiceConnected(MqttAndroidClient.java:111)
        at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1943)
        at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1975)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)`

感觉是android:process=":andmqtt"的问题 导致不同进程了。我跑demo时没问题的
`<service
            android:name="org.eclipse.paho.android.service.MqttService"
            android:enabled="true"
            android:exported="true"
            android:process=":andmqtt" />`

**Comment by Liberations** [comment]
去除这句话android:process=":andmqtt" 即可。。。
暂时没找更好的解决办法

**Comment by Reathin** [comment]
> 去除这句话android:process=":andmqtt" 即可。。。
> 暂时没找更好的解决办法

android:process 我没加这个属性  所以没注意到上面的问题。
这应该是跨进程通信引起的，我看看有没有办法解决。
